# Generated by Django 4.2 on 2024-11-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrvX8szwybkA8_2wFG8BrFkHVcQJFaVA6H_g&s', max_length=500),
        ),
    ]
